config/routes.rb
Rails.application.routes.draw do
  devise_for :views
  devise_for :users
  root to: 'boards#index'
  resources :users, only:[:edit, :update]
  resources :boards, only:[:index, :new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :groups
  has_many :users

  validates :title, :content, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages
  belongs_to :board
  validates :name, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/users_group.rb
class UsersGroup < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  def index
    @boards = Board.all
  end

  def new
    @board = Board.new
  end

  def create
    Board.create(boards_params)
    redirect_to root_path
  end

    def show
      
    end

  private

  def boards_params
    params.require(:board).permit(:title, :content)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/index.html.haml
%body
  .board-wrapper
    .board-wrapper__header
      %h1.header-title Welcome!　chat-boards
    .board-wrapper__container
      .board-wrapper__link-box
        %ul.link-box__left
          %li.link-box__left_login
            %h1 login
            = link_to("login!",view_session_path, {class: "login-font"})

          %li.link-box__left__create
            %h1 sign up!

        %ul.link-box__right
          %li.link-box__right_facebook
            %h1 facebook
            = link_to("facebook","https://ja-jp.facebook.com/", {class: "facebook-font"})
          %li.link-box__right_twitter
            %h1 twitter
            = link_to("twitter","https://twitter.com/login?lang=ja", {class: "twitter-font"})

app/views/boards/new.html.haml
.board-wrapper
  .board-wrapper__header
    .board-wrapper__header__left
      Let's write a headline!
    .board-wrapper__header__right
      HOME
  .board-wrapper__container
    .board-wrapper__container__box
      = form_with(model: @board, local: true,class: :form_box) do |form|
        = form.text_area :title, placeholder: "タイトル", size: "100x5",class: :form_title
        = form.text_area :content,placeholder: "あなたのchatを紹介してください", size: "100x30", class: :form_content
        = form.submit 'PUSH',class: :form__btn

app/views/boards/show.html.haml
.board-wrapper
  .board-wrapper__header
    
  .board-wrapper__center
    .board-wrapper_upper
      
    .board-wrapper_bottom
      Go to Chat

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatBoards
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = yield

app/views/users/_edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header-login
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", 'root_path', class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", '#', class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'